name: CI - email step

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: '23f1002747@ds.study.iitm.ac.in'
        run: echo "Hello from step named with the required email"

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache
          key: cache-fa0d770

      - name: prime-cache-fa0d770
        run: echo "Cache result => ${{ steps.cache.outputs.cache-hit }}"
